version: '3.1'
services:
 mysql_server:
  image: mysql:8
  restart: always
  environment:
    TZ: Asia/Shanghai
    MYSQL_ROOT_PASSWORD: "test"
    MYSQL_USER: 'test'
    MYSQL_PASSWORD: 'test'
    MYSQL_DATABASE:  'test'
    COMPOSE_HTTP_TIMEOUT: 20
  command:
    --default-authentication-plugin=mysql_native_password
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_general_ci
    --explicit_defaults_for_timestamp=true
    --lower_case_table_names=1
    --max_allowed_packet=128M;
  ports:
    - 3306:3306